version: '3.8'

services:
  sdd-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - PLUGIN_DIR=/app/plugins
      - TEMPLATE_DIR=/app/templates
      - DATA_DIR=/app/data
      - DEFAULT_LANG=en
      - MAX_PLUGINS=50
      - HOOK_TIMEOUT=10000
    volumes:
      # Mount volumes for persistent data
      - ./plugins:/app/plugins:ro
      - ./templates:/app/templates:ro
      - sdd_data:/app/data:rw  # Data directory needs write access
    restart: unless-stopped
    # Note: Health check removed due to distroless image (no shell access)
    # Health monitoring should be handled externally
    
    # Security configurations
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    # Minimal capabilities for Node.js runtime
    cap_add:
      - SETUID
      - SETGID
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    
    networks:
      - sdd-network

  # Optional: Redis for session management and caching
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - sdd-network
    restart: unless-stopped

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - sdd-mcp-server
    networks:
      - sdd-network
    restart: unless-stopped

networks:
  sdd-network:
    driver: bridge

volumes:
  sdd_data:
    driver: local
  redis_data:
    driver: local