import { ROLE_MODEL_ROUTES, SKILL_AGENT_ROUTES } from '../install-target.js';
import type { ModelRoutes } from '../model-role-config.js';

/** OMP skills are prompt files; only an extension can change the parent session's model. */
export function renderOmpSkillRouting(routes: ModelRoutes = ROLE_MODEL_ROUTES): string {
  const selectors = Object.fromEntries(Object.entries(SKILL_AGENT_ROUTES).map(([skill, role]) => [skill, routes[role].omp]));
  return `// Generated by sdd-mcp-server. OMP ignores model fields in SKILL.md.
const routes = ${JSON.stringify(selectors)};
const invocation = /^\\[IMPORTANT: User invoked the "([^"\\n]+)" skill; follow its instructions\\. Full skill below\\.\\]/;

export default function (pi) {
  let previous;
  pi.on('before_agent_start', async (event, ctx) => {
    if (ctx.agent.kind !== 'main') return;
    const match = invocation.exec(event.prompt);
    if (!match || !Object.hasOwn(routes, match[1])) return;
    const route = routes[match[1]];
    const model = ctx.models.resolve(route.model);
    if (!model) {
      ctx.ui.notify('SDD skill ' + match[1] + ': configured model ' + route.model + ' is unavailable; select an installed model or reinstall with --model-roles.', 'error');
      ctx.abort();
      return;
    }
    const original = previous ?? { model: ctx.models.current(), thinking: pi.getThinkingLevel() };
    if (!await pi.setModel(model)) {
      ctx.ui.notify('SDD skill ' + match[1] + ': no credentials for ' + route.model + '.', 'error');
      ctx.abort();
      return;
    }
    previous = original;
    pi.setThinkingLevel(route.thinkingLevel);
  });
  pi.on('agent_end', async (_event, ctx) => {
    if (ctx.agent.kind !== 'main' || !previous) return;
    const restore = previous;
    previous = undefined;
    if (restore.model) await pi.setModel(restore.model);
    if (restore.thinking) pi.setThinkingLevel(restore.thinking);
  });
}
`;
}
